import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { auth } from "../lib/firebase";


export default function Home() {
  const [user, setUser] = useState(null)
  // const { authUser, loading, signout } = useAuth();
  const router = useRouter();
  const HandleSignout = () => {
    signOut(auth).then(() => {
      // Sign-out successful.
    }).catch((error) => {
      // An error happened.
    });
  }
  // Listen for changes on loading and authUser, redirect if needed
  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if (!user) {
        router.push("/login");
      }
      setUser(user)

    })

  }, [auth, router]);
  console.log(user)
  return (
    <div>
      <Head>
        <title>Habit Tracker App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        {user && (
          <div>
            {/* {JSON.stringify(user, null, 2)} */}
            <p>Congratulations {user?.displayName} ! You are logged in.</p>

          </div>
        )}
        <button onClick={HandleSignout}>Sign out</button>
      </main>
    </div>
  );
}
